SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d')
FROM MEMBER_PROFILE M INNER JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_ID = 
(
    SELECT MEMBER_ID FROM 
        (
            SELECT MEMBER_ID,COUNT(MEMBER_ID) 
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
            ORDER BY COUNT(MEMBER_ID) DESC
            LIMIT 1
        )
    AS NEW
)
ORDER BY R.REVIEW_DATE,R.REVIEW_TEXT;